version: '2'

services:

  geoservice:
    build:
      context: .
      dockerfile: ./.docker/geoservice.development.dockerfile
    command: npm start
    container_name: geoservice-start
    image: geoservice
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
