settings:
  determineRouteBeforeAppMiddleware: true
  displayErrorDetails: true
  doctrine:
    meta:
      entity_path:
      - app/src/Entity
      auto_generate_proxies: true
      proxy_dir: D:\geo-services\api\config/../cache/proxies
      cache: 
    connection:
      driver: pdo_mysql
      host: localhost
      dbname: geo_service
      user: root
      port: '3306'
      password: Und3rTh3D@rk
    authentication:
      orm_default:
        object_manager: Doctrine\ORM\EntityManager
        identity_class: GeoService\Users\Users
        identity_property: email
        credential_property: password
      service_manager:
        factories:
          Zend\Authentication\AuthenticationService: GeoService\Users\Service\Factory\AuthenticationServiceFactory
  logger:
    name: app
    path: D:\geo-services\api\config/../log/app.log
  allowed_origin: http://localhost:5555
  caching:
    abstract_factories:
    - Zend\Cache\Service\StorageCacheAbstractServiceFactory
    caches:
      GeoSevice:
        adapter:
          name: memcache
          options:
            servers:
              - localhost
              - 11211
            namespace: GeoSevice
            ttl: 300
  cors:
    origin: http://localhost:5555
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    headers.allow: []
    headers.expose: []
    credentials: true
    cache: 0
    error: null
    logger: null
