export const SOMETHING_HAPPENED_SUCCESSFULLY =
  'SOMETHING_HAPPENED_SUCCESSFULLY';
export const SOMETHING_FAILED = 'SOMETHING_FAILED';

export const TOGGLED_ON = 'TOGGLED_ON';
export const TOGGLED_OFF = 'TOGGLED_OFF';
