import { ABOUT_COMPONENT_DECLARATIONS } from './about/common';
import { HOME_COMPONENT_DECLARATIONS } from './home/common';
import { MENU_COMPONENT_DECLARATIONS } from './menu/common';
import { I18N_COMPONENT_DECLARATIONS } from './i18n/common';

export const COMPONENT_DECLARATIONS: Array<any> = [
    ...ABOUT_COMPONENT_DECLARATIONS,
    ...HOME_COMPONENT_DECLARATIONS,
    ...MENU_COMPONENT_DECLARATIONS,
    ...I18N_COMPONENT_DECLARATIONS
];
