import { MAINMENU_COMPONENT_DECLARATIONS, MAINMENU_COMPONENT_EXPORTS } from './main-menu';
import { SIGNIN_COMPONENT_DECLARATIONS, SIGNIN_COMPONENT_EXPORTS, SIGNIN_ROUTES } from './signin';

export const COMPONENT_DECLARATIONS: Array<any> = [
    ...MAINMENU_COMPONENT_DECLARATIONS,
    ...SIGNIN_COMPONENT_DECLARATIONS
];

export const COMPONENT_EXPORTS: Array<any> = [
    ...MAINMENU_COMPONENT_EXPORTS,
    ...SIGNIN_COMPONENT_EXPORTS
];

export const COMPONENT_ROUTES: Array<any> = [
    ...SIGNIN_ROUTES
];
