settings:
  determineRouteBeforeAppMiddleware: true
  displayErrorDetails: true
  useSimpleAnnotationReader: false
  mode: null
  doctrine:
    dbal:
      charset: utf8mb4
      default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci
    meta:
      entity_path:
      - app/src/Entity
      auto_generate_proxies: true
      proxy_dir: D:\geo-services\api\config/../cache/proxies
      cache: null
    connection:
      driver: pdo_mysql
      host: localhost
      dbname: geo_service
      user: root
      port: '3306'
      password: Und3rTh3D@rk
  logger:
    name: app
    path: D:\geo-services\api\config/../logs/app.log
  caching:
    abstract_factories:
    - Zend\Cache\Service\StorageCacheAbstractServiceFactory
    caches:
      GeoSevice:
        adapter:
          name: memcache
          options:
            servers:
              - localhost
              - 11211
            namespace: GeoSevice
            ttl: 300
  cors:
    origin: 
    - 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop'
    - 'http://localhost:5556'
    methods:
    - 'GET'
    - 'POST'
    - 'PUT'
    - 'PATCH'
    - 'DELETE'
    - 'REQUEST'
    headers.allow: 
    - 'X-Requested-With'
    - 'Content-Type'
    - 'Accept'
    - 'Origin'
    - 'Authorization'
    headers.expose:
    -
    credentials: true
    cache: 86400
    error: null
    logger: null
  messages:
    validation:
      user:
        not_found: 'No user found with that id.'
      address:
        not_found: 'No address found with that id.'
  mail: '%parameters.host%'