settings:
  determineRouteBeforeAppMiddleware: true
  displayErrorDetails: true
  doctrine:
    dbal:
      charset: utf8mb4
      default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci  
    meta:
      entity_path:
      - app/src/Entity
      auto_generate_proxies: true
      proxy_dir: proxy_dir
      cache: 
    connection:
      driver: db_driver
      host: db_host
      dbname: db_name
      user: db_user
      port: db_port
      password: db_user_password
  logger:
    name: app
    path: logger_path
  caching:
    abstract_factories:
    - Zend\Cache\Service\StorageCacheAbstractServiceFactory
    caches:
      GeoSevice:
        adapter:
          name: memcache
          options:
            servers:
              - server_name
              - server_port
            namespace: GeoSevice
            ttl: 300
  cors:
    origin: origin
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    headers.allow: []
    headers.expose: []
    credentials: true
    cache: 0
    error: null
    logger: null
