settings:
  determineRouteBeforeAppMiddleware: true
  displayErrorDetails: true
  useSimpleAnnotationReader: false
  mode: null
  doctrine:
    dbal:
      charset: utf8mb4
      default_table_options:
        charset: utf8mb4
        collate: utf8mb4_unicode_ci  
    meta:
      entity_path:
      - app/src/Entity
      auto_generate_proxies: true
      proxy_dir: proxy_dir
      cache: 
    connection:
      driver: db_driver
      host: db_host
      dbname: db_name
      user: db_user
      port: db_port
      password: db_user_password
  logger:
    name: app
    path: logger_path
  caching:
    abstract_factories:
    - Zend\Cache\Service\StorageCacheAbstractServiceFactory
    caches:
      GeoSevice:
        adapter:
          name: memcache
          options:
            servers:
              - server_name
              - server_port
            namespace: GeoSevice
            ttl: 300
  cors:
    origin: 
    - null
    methods:
    - null
    headers.allow: 
    - null
    headers.expose:
    -
    credentials: true
    cache: 86400
    error: null
    logger: null
  messages:
    validation:
      user:
        not_found: 'No user found with that id.'
      address:
        not_found: 'No address found with that id.'